Added ability to dump azure cloud inventory
adobe/cloudinventory pull request #1
Opened 2019-05-10 21:19 UTC by another-maverick

Added ability to dump azure cloud inventory. A new sub command "azure" has been added. It takes filters to dump virtual machine and db inventory

The code accepts azure credentials from the environment and determines what subscriptions that teh credentials have access to.
Based on the filters supplied, it calls Azure API's and extracts the details. 
The code runs in a concurrent fashion across all the subscriptions. wait group hs been created to ensure the completion of all go routines.
Cmd line args are accepted via cobra

## Motivation and Context

Currently, the tool only extracts AWS cloud inventory. The changes gives the ability to extract cloud inventory from Azure

## How Has This Been Tested?

Created an image using the docker file. 
Passed Azure credentials as run time environment variables and tested with all subcommands. Also tested the combinations using flags
Logged into the docker layer and verified if the data is being dumped into the file specified by the --path flag
Passed incorrect creds and verified error messages. Tested for impact on existing code

The changes are isolated from the existing AWS code. 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

2019-05-11 05:37 UTC, tchaudhry91 commented
Thanks Rakesh. I'll review this

2019-05-22 09:58 UTC, tchaudhry91 commented on Dockerfile
> +RUN  go get -u github.com/Azure/azure-sdk-for-go
With Go Modules, we shouldn't have to specify all the dependencies like this in the Dockerfile. I think simply doing a `go mod tidy` should do the trick.

2019-05-22 10:00 UTC, tchaudhry91 commented on azurelib/azureBase.go
> +	envVars := []string{"AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET"}
This is probably good for the first release, but we'll soon need to allow a way to have more types of credential input. 
I'm not super familiar with Azure but I assume it has something equivalent to shared creds file/IAM style auth?

2019-05-22 10:05 UTC, tchaudhry91 requested changes
I think we need to find a way to remove the fmt.Printx statements within the library. Having console prints inside the package will severly limit it's usability as an importable library. 
Also, I see a lot of the structs have been custom defined, does the azure SDK not have their own struct definitions which we can simply marshal/unmarshal?
I'll do a deeper review and see options to fix the points above :)
Thanks again for the effort!

2019-06-04 00:10 UTC, another-maverick commented on Dockerfile
> +RUN  go get -u github.com/Azure/azure-sdk-for-go
Good point, Tanmay.  I used go mod tidy
Also, i tried to download dependencies and cache the go modules to reduce the build time for subsequent builds.. Build would run again if go.mod and go.sum change

2019-06-04 00:12 UTC, another-maverick commented on azurelib/azureBase.go
> +	envVars := []string{"AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET"}
I thought capturing credentials from env would make the app more in sync with 12-factor principles. Having said this, We can certainly use a credentials file(json/yaml) and make git ignore it. It is straightforward, I just need to change the authorizer to get creds from a file instead of the environment. Please let me know your thoughts.

2019-06-04 00:33 UTC, another-maverick commented
> I think we need to find a way to remove the fmt.Printx statements within the library. Having console prints inside the package will severly limit it's usability as an importable library.
> Also, I see a lot of the structs have been custom defined, does the azure SDK not have their own struct definitions which we can simply marshal/unmarshal?
> I'll do a deeper review and see options to fix the points above :)
> Thanks again for the effort!

The print statements in the package were added just for troubleshooting during the development phase. I added logging ability to capture relevant information instead. 
Reg custom structs: Azure defines everything as a resource (IP is a resource, VM is a resource etc) all of them have a resourceID, and when we query VM list, for example, we need to recursively parse it and extract resourceID's of NIC and then one more recursion to get privateIP etc.  In short, I had to define custom structs to club data together. When I dig deeper into the docs, I see I can get rid of some of the structs and use Azure provided ones. I will work on cleaning it up.

2019-06-04 23:49 UTC, another-maverick commented
Additional Note from the observations reg custom structs:
- I have tried using the OOB structs. There are issues with Azure API's, for example: when we list VM's, the expected result is a slice of type VM.  Out of no where, I found a NIC resource in it.
- Problem: The VM type has a few fields whole values are pointers. One example is "ComputerName". For a NIC resource, computerName is "nil". Hence the memory address is invalid and there would be nil pointer dereference. This is sporadic, and on random resources.(need to report this and work with Microsoft)  
- When using custom structs, the problem can be avoided since I am converting the reource to a byte string array and then to a struct that does not look for pointers. When the above bug is encountered, the value would be empty(nil)

2020-06-13 14:08 UTC, tchaudhry91 commented
Archiving. This project is being re-ignited and some structure will change. Thanks @another-maverick for your efforts! We'll try to re-use this as much as possible

2020-06-13 14:08 UTC, closed without merging